// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1TripPlanner.proto

package ds.service1;

public interface forecastTrafficStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.forecastTrafficStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
