// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dynamicTrafficControl.proto

package com.caone;

public interface currentLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dynamic.currentLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitudeCur = 1;</code>
   */
  double getLatitudeCur();

  /**
   * <code>double longitudeCur = 2;</code>
   */
  double getLongitudeCur();
}
