// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dynamicTrafficControl.proto

package com.caone;

public interface currentLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dynamic.currentLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitudeCur = 1;</code>
   */
  int getLatitudeCur();

  /**
   * <code>int32 longitudeCur = 2;</code>
   */
  int getLongitudeCur();
}
