// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dynamicTrafficControl.proto

package com.caone;

public final class DynamicTrafficControlImpl {
  private DynamicTrafficControlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dynamic_currentLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dynamic_currentLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dynamic_trafficUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dynamic_trafficUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dynamic_registration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dynamic_registration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dynamic_registrationStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dynamic_registrationStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033dynamicTrafficControl.proto\022\007dynamic\"<" +
      "\n\017currentLocation\022\023\n\013latitudeCur\030\001 \001(\001\022\024" +
      "\n\014longitudeCur\030\002 \001(\001\"\037\n\rtrafficUpdate\022\016\n" +
      "\006update\030\001 \001(\t\"/\n\014registration\022\020\n\010userNam" +
      "e\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\"$\n\022registrationSt" +
      "atus\022\016\n\006status\030\001 \001(\t2\236\001\n\025DynamicTrafficC" +
      "ontrol\022B\n\nliveUpdate\022\030.dynamic.currentLo" +
      "cation\032\026.dynamic.trafficUpdate\"\0000\001\022A\n\007us" +
      "erOps\022\025.dynamic.registration\032\033.dynamic.r" +
      "egistrationStatus\"\000(\001B(\n\tcom.caoneB\031Dyna" +
      "micTrafficControlImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dynamic_currentLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dynamic_currentLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dynamic_currentLocation_descriptor,
        new java.lang.String[] { "LatitudeCur", "LongitudeCur", });
    internal_static_dynamic_trafficUpdate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dynamic_trafficUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dynamic_trafficUpdate_descriptor,
        new java.lang.String[] { "Update", });
    internal_static_dynamic_registration_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dynamic_registration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dynamic_registration_descriptor,
        new java.lang.String[] { "UserName", "Email", });
    internal_static_dynamic_registrationStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_dynamic_registrationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dynamic_registrationStatus_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
