// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficStatus.proto

package com.caone;

public interface futureTrafficRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traffic.futureTrafficRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitudeCur = 1;</code>
   */
  double getLatitudeCur();

  /**
   * <code>double longitudeCur = 2;</code>
   */
  double getLongitudeCur();

  /**
   * <code>double latitudeDes = 3;</code>
   */
  double getLatitudeDes();

  /**
   * <code>double longitudeDes = 4;</code>
   */
  double getLongitudeDes();

  /**
   * <code>double departureTime = 5;</code>
   */
  double getDepartureTime();
}
