// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficStatus.proto

package com.caone;

public interface futureTrafficRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traffic.futureTrafficRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 latitudeCur = 1;</code>
   */
  int getLatitudeCur();

  /**
   * <code>int32 longitudeCur = 2;</code>
   */
  int getLongitudeCur();

  /**
   * <code>int32 latitudeDes = 3;</code>
   */
  int getLatitudeDes();

  /**
   * <code>int32 longitudeDes = 4;</code>
   */
  int getLongitudeDes();

  /**
   * <code>string departureTime = 5;</code>
   */
  java.lang.String getDepartureTime();
  /**
   * <code>string departureTime = 5;</code>
   */
  com.google.protobuf.ByteString
      getDepartureTimeBytes();
}
