// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dynamicTrafficControl.proto

package com.caone;

public interface registrationStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dynamic.registrationStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
