// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dynamicTrafficControl.proto

package com.caone;

public final class TrafficMngmtImpl {
  private TrafficMngmtImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caone_currentLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caone_currentLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caone_trafficUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caone_trafficUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caone_registration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caone_registration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_caone_registrationStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_caone_registrationStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033dynamicTrafficControl.proto\022\005caone\"<\n\017" +
      "currentLocation\022\023\n\013latitudeCur\030\001 \001(\005\022\024\n\014" +
      "longitudeCur\030\002 \001(\005\"\037\n\rtrafficUpdate\022\016\n\006u" +
      "pdate\030\001 \001(\t\"/\n\014registration\022\020\n\010userName\030" +
      "\001 \001(\t\022\r\n\005email\030\002 \001(\t\"$\n\022registrationStat" +
      "us\022\016\n\006status\030\001 \001(\t2\226\001\n\025DynamicTrafficCon" +
      "trol\022>\n\nliveUpdate\022\026.caone.currentLocati" +
      "on\032\024.caone.trafficUpdate\"\0000\001\022=\n\007userOps\022" +
      "\023.caone.registration\032\031.caone.registratio" +
      "nStatus\"\000(\001B\037\n\tcom.caoneB\020TrafficMngmtIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_caone_currentLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_caone_currentLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caone_currentLocation_descriptor,
        new java.lang.String[] { "LatitudeCur", "LongitudeCur", });
    internal_static_caone_trafficUpdate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_caone_trafficUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caone_trafficUpdate_descriptor,
        new java.lang.String[] { "Update", });
    internal_static_caone_registration_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_caone_registration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caone_registration_descriptor,
        new java.lang.String[] { "UserName", "Email", });
    internal_static_caone_registrationStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_caone_registrationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_caone_registrationStatus_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
