// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficStatus.proto

package com.caone;

public final class TrafficStatusImpl {
  private TrafficStatusImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_trafficRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_trafficRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_futureTrafficRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_futureTrafficRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_trafficStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_trafficStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traffic_forecastTrafficStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traffic_forecastTrafficStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023trafficStatus.proto\022\007traffic\"f\n\016traffi" +
      "cRequest\022\023\n\013latitudeCur\030\001 \001(\005\022\024\n\014longitu" +
      "deCur\030\002 \001(\005\022\023\n\013latitudeDes\030\003 \001(\005\022\024\n\014long" +
      "itudeDes\030\004 \001(\005\"\203\001\n\024futureTrafficRequest\022" +
      "\023\n\013latitudeCur\030\001 \001(\005\022\024\n\014longitudeCur\030\002 \001" +
      "(\005\022\023\n\013latitudeDes\030\003 \001(\005\022\024\n\014longitudeDes\030" +
      "\004 \001(\005\022\025\n\rdepartureTime\030\005 \001(\t\" \n\rtrafficS" +
      "tatus\022\017\n\007message\030\001 \001(\t\"%\n\025forecastTraffi" +
      "cStatus\022\014\n\004name\030\001 \001(\t2\250\001\n\rCurrentStatus\022" +
      "B\n\rcurrentStatus\022\027.traffic.trafficReques" +
      "t\032\026.traffic.trafficStatus\"\000\022S\n\014futureSta" +
      "tus\022\035.traffic.futureTrafficRequest\032\036.tra" +
      "ffic.forecastTrafficStatus\"\000(\0010\001B \n\tcom." +
      "caoneB\021TrafficStatusImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_traffic_trafficRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_traffic_trafficRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_trafficRequest_descriptor,
        new java.lang.String[] { "LatitudeCur", "LongitudeCur", "LatitudeDes", "LongitudeDes", });
    internal_static_traffic_futureTrafficRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_traffic_futureTrafficRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_futureTrafficRequest_descriptor,
        new java.lang.String[] { "LatitudeCur", "LongitudeCur", "LatitudeDes", "LongitudeDes", "DepartureTime", });
    internal_static_traffic_trafficStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_traffic_trafficStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_trafficStatus_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_traffic_forecastTrafficStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_traffic_forecastTrafficStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traffic_forecastTrafficStatus_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
