// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficStatus.proto

package com.caone;

public interface trafficRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trafficStatus.trafficRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currentdestination = 1;</code>
   */
  java.lang.String getCurrentdestination();
  /**
   * <code>string currentdestination = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrentdestinationBytes();

  /**
   * <code>string desireddestination = 2;</code>
   */
  java.lang.String getDesireddestination();
  /**
   * <code>string desireddestination = 2;</code>
   */
  com.google.protobuf.ByteString
      getDesireddestinationBytes();
}
