// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficStatus.proto

package com.caone;

/**
 * Protobuf type {@code trafficStatus.trafficRequest}
 */
public  final class trafficRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trafficStatus.trafficRequest)
    trafficRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use trafficRequest.newBuilder() to construct.
  private trafficRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  trafficRequest() {
    currentdestination_ = "";
    desireddestination_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private trafficRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            currentdestination_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            desireddestination_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.caone.TrafficMngmtImpl.internal_static_trafficStatus_trafficRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.caone.TrafficMngmtImpl.internal_static_trafficStatus_trafficRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.caone.trafficRequest.class, com.caone.trafficRequest.Builder.class);
  }

  public static final int CURRENTDESTINATION_FIELD_NUMBER = 1;
  private volatile java.lang.Object currentdestination_;
  /**
   * <code>string currentdestination = 1;</code>
   */
  public  java.lang.String getCurrentdestination() {
    java.lang.Object ref = currentdestination_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentdestination_ = s;
      return s;
    }
  }
  /**
   * <code>string currentdestination = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCurrentdestinationBytes() {
    java.lang.Object ref = currentdestination_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentdestination_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESIREDDESTINATION_FIELD_NUMBER = 2;
  private volatile java.lang.Object desireddestination_;
  /**
   * <code>string desireddestination = 2;</code>
   */
  public java.lang.String getDesireddestination() {
    java.lang.Object ref = desireddestination_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desireddestination_ = s;
      return s;
    }
  }
  /**
   * <code>string desireddestination = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDesireddestinationBytes() {
    java.lang.Object ref = desireddestination_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desireddestination_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCurrentdestinationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentdestination_);
    }
    if (!getDesireddestinationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, desireddestination_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCurrentdestinationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentdestination_);
    }
    if (!getDesireddestinationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, desireddestination_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.caone.trafficRequest)) {
      return super.equals(obj);
    }
    com.caone.trafficRequest other = (com.caone.trafficRequest) obj;

    boolean result = true;
    result = result && getCurrentdestination()
        .equals(other.getCurrentdestination());
    result = result && getDesireddestination()
        .equals(other.getDesireddestination());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENTDESTINATION_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentdestination().hashCode();
    hash = (37 * hash) + DESIREDDESTINATION_FIELD_NUMBER;
    hash = (53 * hash) + getDesireddestination().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.caone.trafficRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caone.trafficRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caone.trafficRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caone.trafficRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caone.trafficRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caone.trafficRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caone.trafficRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caone.trafficRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caone.trafficRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.caone.trafficRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caone.trafficRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caone.trafficRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.caone.trafficRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code trafficStatus.trafficRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trafficStatus.trafficRequest)
      com.caone.trafficRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caone.TrafficMngmtImpl.internal_static_trafficStatus_trafficRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caone.TrafficMngmtImpl.internal_static_trafficStatus_trafficRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caone.trafficRequest.class, com.caone.trafficRequest.Builder.class);
    }

    // Construct using com.caone.trafficRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentdestination_ = "";

      desireddestination_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.caone.TrafficMngmtImpl.internal_static_trafficStatus_trafficRequest_descriptor;
    }

    @java.lang.Override
    public com.caone.trafficRequest getDefaultInstanceForType() {
      return com.caone.trafficRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.caone.trafficRequest build() {
      com.caone.trafficRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.caone.trafficRequest buildPartial() {
      com.caone.trafficRequest result = new com.caone.trafficRequest(this);
      result.currentdestination_ = currentdestination_;
      result.desireddestination_ = desireddestination_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.caone.trafficRequest) {
        return mergeFrom((com.caone.trafficRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.caone.trafficRequest other) {
      if (other == com.caone.trafficRequest.getDefaultInstance()) return this;
      if (!other.getCurrentdestination().isEmpty()) {
        currentdestination_ = other.currentdestination_;
        onChanged();
      }
      if (!other.getDesireddestination().isEmpty()) {
        desireddestination_ = other.desireddestination_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.caone.trafficRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.caone.trafficRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object currentdestination_ = "";
    /**
     * <code>string currentdestination = 1;</code>
     */
    public java.lang.String getCurrentdestination() {
      java.lang.Object ref = currentdestination_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentdestination_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currentdestination = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCurrentdestinationBytes() {
      java.lang.Object ref = currentdestination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentdestination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currentdestination = 1;</code>
     */
    public Builder setCurrentdestination(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currentdestination_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string currentdestination = 1;</code>
     */
    public Builder clearCurrentdestination() {
      
      currentdestination_ = getDefaultInstance().getCurrentdestination();
      onChanged();
      return this;
    }
    /**
     * <code>string currentdestination = 1;</code>
     */
    public Builder setCurrentdestinationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currentdestination_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object desireddestination_ = "";
    /**
     * <code>string desireddestination = 2;</code>
     */
    public java.lang.String getDesireddestination() {
      java.lang.Object ref = desireddestination_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desireddestination_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string desireddestination = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDesireddestinationBytes() {
      java.lang.Object ref = desireddestination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desireddestination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string desireddestination = 2;</code>
     */
    public Builder setDesireddestination(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      desireddestination_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string desireddestination = 2;</code>
     */
    public Builder clearDesireddestination() {
      
      desireddestination_ = getDefaultInstance().getDesireddestination();
      onChanged();
      return this;
    }
    /**
     * <code>string desireddestination = 2;</code>
     */
    public Builder setDesireddestinationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      desireddestination_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trafficStatus.trafficRequest)
  }

  // @@protoc_insertion_point(class_scope:trafficStatus.trafficRequest)
  private static final com.caone.trafficRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.caone.trafficRequest();
  }

  public static com.caone.trafficRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<trafficRequest>
      PARSER = new com.google.protobuf.AbstractParser<trafficRequest>() {
    @java.lang.Override
    public trafficRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new trafficRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<trafficRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<trafficRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.caone.trafficRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

