// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dynamicTrafficControl.proto

package com.caone;

public interface trafficUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dynamic.trafficUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string update = 1;</code>
   */
  java.lang.String getUpdate();
  /**
   * <code>string update = 1;</code>
   */
  com.google.protobuf.ByteString
      getUpdateBytes();
}
