// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficStatus.proto

package com.caone;

public final class TrafficMngmtImpl {
  private TrafficMngmtImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficStatus_trafficRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficStatus_trafficRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficStatus_trafficStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficStatus_trafficStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_trafficStatus_forecastTrafficStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_trafficStatus_forecastTrafficStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023trafficStatus.proto\022\rtrafficStatus\"H\n\016" +
      "trafficRequest\022\032\n\022currentdestination\030\001 \001" +
      "(\t\022\032\n\022desireddestination\030\002 \001(\t\" \n\rtraffi" +
      "cStatus\022\017\n\007message\030\001 \001(\t\"%\n\025forecastTraf" +
      "ficStatus\022\014\n\004name\030\001 \001(\t2a\n\rCurrentStatus" +
      "\022P\n\rcurrentStatus\022\035.trafficStatus.traffi" +
      "cRequest\032\034.trafficStatus.trafficStatus\"\000" +
      "(\0012i\n\014FutureStatus\022Y\n\014futureStatus\022\035.tra" +
      "fficStatus.trafficRequest\032$.trafficStatu" +
      "s.forecastTrafficStatus\"\000(\0010\001B\037\n\tcom.cao" +
      "neB\020TrafficMngmtImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_trafficStatus_trafficRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_trafficStatus_trafficRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficStatus_trafficRequest_descriptor,
        new java.lang.String[] { "Currentdestination", "Desireddestination", });
    internal_static_trafficStatus_trafficStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_trafficStatus_trafficStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficStatus_trafficStatus_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_trafficStatus_forecastTrafficStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_trafficStatus_forecastTrafficStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_trafficStatus_forecastTrafficStatus_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
