// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trafficStatus.proto

package com.caone;

/**
 * Protobuf type {@code traffic.trafficRequest}
 */
public  final class trafficRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:traffic.trafficRequest)
    trafficRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use trafficRequest.newBuilder() to construct.
  private trafficRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private trafficRequest() {
    latitudeCur_ = 0D;
    longitudeCur_ = 0D;
    latitudeDes_ = 0D;
    longitudeDes_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private trafficRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            latitudeCur_ = input.readDouble();
            break;
          }
          case 17: {

            longitudeCur_ = input.readDouble();
            break;
          }
          case 25: {

            latitudeDes_ = input.readDouble();
            break;
          }
          case 33: {

            longitudeDes_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.caone.TrafficStatusImpl.internal_static_traffic_trafficRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.caone.TrafficStatusImpl.internal_static_traffic_trafficRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.caone.trafficRequest.class, com.caone.trafficRequest.Builder.class);
  }

  public static final int LATITUDECUR_FIELD_NUMBER = 1;
  private double latitudeCur_;
  /**
   * <code>double latitudeCur = 1;</code>
   */
  public double getLatitudeCur() {
    return latitudeCur_;
  }

  public static final int LONGITUDECUR_FIELD_NUMBER = 2;
  private double longitudeCur_;
  /**
   * <code>double longitudeCur = 2;</code>
   */
  public double getLongitudeCur() {
    return longitudeCur_;
  }

  public static final int LATITUDEDES_FIELD_NUMBER = 3;
  private double latitudeDes_;
  /**
   * <code>double latitudeDes = 3;</code>
   */
  public double getLatitudeDes() {
    return latitudeDes_;
  }

  public static final int LONGITUDEDES_FIELD_NUMBER = 4;
  private double longitudeDes_;
  /**
   * <code>double longitudeDes = 4;</code>
   */
  public double getLongitudeDes() {
    return longitudeDes_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (latitudeCur_ != 0D) {
      output.writeDouble(1, latitudeCur_);
    }
    if (longitudeCur_ != 0D) {
      output.writeDouble(2, longitudeCur_);
    }
    if (latitudeDes_ != 0D) {
      output.writeDouble(3, latitudeDes_);
    }
    if (longitudeDes_ != 0D) {
      output.writeDouble(4, longitudeDes_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (latitudeCur_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, latitudeCur_);
    }
    if (longitudeCur_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, longitudeCur_);
    }
    if (latitudeDes_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, latitudeDes_);
    }
    if (longitudeDes_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, longitudeDes_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.caone.trafficRequest)) {
      return super.equals(obj);
    }
    com.caone.trafficRequest other = (com.caone.trafficRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getLatitudeCur())
        == java.lang.Double.doubleToLongBits(
            other.getLatitudeCur()));
    result = result && (
        java.lang.Double.doubleToLongBits(getLongitudeCur())
        == java.lang.Double.doubleToLongBits(
            other.getLongitudeCur()));
    result = result && (
        java.lang.Double.doubleToLongBits(getLatitudeDes())
        == java.lang.Double.doubleToLongBits(
            other.getLatitudeDes()));
    result = result && (
        java.lang.Double.doubleToLongBits(getLongitudeDes())
        == java.lang.Double.doubleToLongBits(
            other.getLongitudeDes()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LATITUDECUR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLatitudeCur()));
    hash = (37 * hash) + LONGITUDECUR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLongitudeCur()));
    hash = (37 * hash) + LATITUDEDES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLatitudeDes()));
    hash = (37 * hash) + LONGITUDEDES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLongitudeDes()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.caone.trafficRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caone.trafficRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caone.trafficRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caone.trafficRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caone.trafficRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.caone.trafficRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.caone.trafficRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caone.trafficRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caone.trafficRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.caone.trafficRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.caone.trafficRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.caone.trafficRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.caone.trafficRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code traffic.trafficRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:traffic.trafficRequest)
      com.caone.trafficRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.caone.TrafficStatusImpl.internal_static_traffic_trafficRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.caone.TrafficStatusImpl.internal_static_traffic_trafficRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.caone.trafficRequest.class, com.caone.trafficRequest.Builder.class);
    }

    // Construct using com.caone.trafficRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      latitudeCur_ = 0D;

      longitudeCur_ = 0D;

      latitudeDes_ = 0D;

      longitudeDes_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.caone.TrafficStatusImpl.internal_static_traffic_trafficRequest_descriptor;
    }

    @java.lang.Override
    public com.caone.trafficRequest getDefaultInstanceForType() {
      return com.caone.trafficRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.caone.trafficRequest build() {
      com.caone.trafficRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.caone.trafficRequest buildPartial() {
      com.caone.trafficRequest result = new com.caone.trafficRequest(this);
      result.latitudeCur_ = latitudeCur_;
      result.longitudeCur_ = longitudeCur_;
      result.latitudeDes_ = latitudeDes_;
      result.longitudeDes_ = longitudeDes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.caone.trafficRequest) {
        return mergeFrom((com.caone.trafficRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.caone.trafficRequest other) {
      if (other == com.caone.trafficRequest.getDefaultInstance()) return this;
      if (other.getLatitudeCur() != 0D) {
        setLatitudeCur(other.getLatitudeCur());
      }
      if (other.getLongitudeCur() != 0D) {
        setLongitudeCur(other.getLongitudeCur());
      }
      if (other.getLatitudeDes() != 0D) {
        setLatitudeDes(other.getLatitudeDes());
      }
      if (other.getLongitudeDes() != 0D) {
        setLongitudeDes(other.getLongitudeDes());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.caone.trafficRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.caone.trafficRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double latitudeCur_ ;
    /**
     * <code>double latitudeCur = 1;</code>
     */
    public double getLatitudeCur() {
      return latitudeCur_;
    }
    /**
     * <code>double latitudeCur = 1;</code>
     */
    public Builder setLatitudeCur(double value) {
      
      latitudeCur_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double latitudeCur = 1;</code>
     */
    public Builder clearLatitudeCur() {
      
      latitudeCur_ = 0D;
      onChanged();
      return this;
    }

    private double longitudeCur_ ;
    /**
     * <code>double longitudeCur = 2;</code>
     */
    public double getLongitudeCur() {
      return longitudeCur_;
    }
    /**
     * <code>double longitudeCur = 2;</code>
     */
    public Builder setLongitudeCur(double value) {
      
      longitudeCur_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double longitudeCur = 2;</code>
     */
    public Builder clearLongitudeCur() {
      
      longitudeCur_ = 0D;
      onChanged();
      return this;
    }

    private double latitudeDes_ ;
    /**
     * <code>double latitudeDes = 3;</code>
     */
    public double getLatitudeDes() {
      return latitudeDes_;
    }
    /**
     * <code>double latitudeDes = 3;</code>
     */
    public Builder setLatitudeDes(double value) {
      
      latitudeDes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double latitudeDes = 3;</code>
     */
    public Builder clearLatitudeDes() {
      
      latitudeDes_ = 0D;
      onChanged();
      return this;
    }

    private double longitudeDes_ ;
    /**
     * <code>double longitudeDes = 4;</code>
     */
    public double getLongitudeDes() {
      return longitudeDes_;
    }
    /**
     * <code>double longitudeDes = 4;</code>
     */
    public Builder setLongitudeDes(double value) {
      
      longitudeDes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double longitudeDes = 4;</code>
     */
    public Builder clearLongitudeDes() {
      
      longitudeDes_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:traffic.trafficRequest)
  }

  // @@protoc_insertion_point(class_scope:traffic.trafficRequest)
  private static final com.caone.trafficRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.caone.trafficRequest();
  }

  public static com.caone.trafficRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<trafficRequest>
      PARSER = new com.google.protobuf.AbstractParser<trafficRequest>() {
    @java.lang.Override
    public trafficRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new trafficRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<trafficRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<trafficRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.caone.trafficRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

