// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2TrafficUpdates.proto

package ds.service2;

public interface currentLocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.currentLocation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double latitudeCur = 1;</code>
   */
  double getLatitudeCur();

  /**
   * <code>double longitudeCur = 2;</code>
   */
  double getLongitudeCur();
}
