// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2TrafficUpdates.proto

package ds.service2;

public final class DynamicTrafficControlImpl {
  private DynamicTrafficControlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_currentLocation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_currentLocation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_trafficUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_trafficUpdate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_registration_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_registration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_service2_registrationStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_service2_registrationStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034service2TrafficUpdates.proto\022\010service2" +
      "\"<\n\017currentLocation\022\023\n\013latitudeCur\030\001 \001(\001" +
      "\022\024\n\014longitudeCur\030\002 \001(\001\"\037\n\rtrafficUpdate\022" +
      "\016\n\006update\030\001 \001(\t\"/\n\014registration\022\020\n\010userN" +
      "ame\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\"$\n\022registration" +
      "Status\022\016\n\006status\030\001 \001(\t2\233\001\n\016TrafficUpdate" +
      "s\022D\n\nliveUpdate\022\031.service2.currentLocati" +
      "on\032\027.service2.trafficUpdate\"\0000\001\022C\n\007newUs" +
      "er\022\026.service2.registration\032\034.service2.re" +
      "gistrationStatus\"\000(\001B*\n\013ds.service2B\031Dyn" +
      "amicTrafficControlImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_service2_currentLocation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_service2_currentLocation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_currentLocation_descriptor,
        new java.lang.String[] { "LatitudeCur", "LongitudeCur", });
    internal_static_service2_trafficUpdate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_service2_trafficUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_trafficUpdate_descriptor,
        new java.lang.String[] { "Update", });
    internal_static_service2_registration_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_service2_registration_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_registration_descriptor,
        new java.lang.String[] { "UserName", "Email", });
    internal_static_service2_registrationStatus_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_service2_registrationStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_service2_registrationStatus_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
