// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2TrafficUpdates.proto

package ds.service2;

public interface registrationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.registration)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
