// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2TrafficUpdates.proto

package ds.service2;

public interface registrationStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.registrationStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
